resources: [../../base]
namespace: creator-store
labels: [{ pairs: { topology.creator-store/region: region-b } }]
patches:
  - target: { kind: Ingress, name: creator-store-web }
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: creator.region-b.example.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: creator.region-b.example.com
